messages:
  error_command: "Something went wrong while running your command."
  error_download: "I couldn't find that video."
  error_interaction: "Invalid interaction."
  error_permissions: "I don't have permission to do that."
  error_source: "I couldn't find an audio source for that video."
  error_unknown: "An unknown error occurred."
  event_bot_voiceless: "I'm not in a voice channel."
  event_leave: "Bye."
  event_looping_disabled: "Looping disabled."
  event_looping_enabled: "Looping enabled."
  event_not_paused: "I'm not paused."
  event_not_playing: "I'm not playing anything."
  event_play: "Working..."
  event_queue_cleared: "Queue cleared."
  event_queue_empty: "The queue is empty."
  event_track_paused: "Paused."
  event_track_resumed: "Resumed."
  event_track_skipped: "Skipped."
  event_user_voiceless: "You're not in a voice channel."
  help: "`/play`\nPlay track given a YouTube URL.\n\n`/pause`\nPause the current track.\n\n`/resume`\nResume the paused track.\n\n`/loop`\nToggle looping for the current track.\n\n`/queue`\nShow the queue.\n\n`/skip`\nSkip the current track.\n\n`/clear`\nClear the queue.\n\n`/leave`\nStop the current track, clear the queue, and disconnect."
